# Generated by Django 4.0.3 on 2022-09-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employeep',
            new_name='Employee',
        ),
    ]
